trained_model_dir: results/final/stage_2/2025-10-24__21-30-50
config_filename: config.yaml
checkpoint_path: checkpoints/best_valid.pth
indices_csv_path: data/pll_generated_tokens.csv
output_base_dir: inference_decode_results
batch_size: 32
num_workers: 4
max_length: null
mixed_precision: bf16
tqdm_progress_bar: true
compile_model:
  enabled: false
  mode: null
