id_to_token:
  0: <PAD>
  1: <BOS>
  2: <EOS>
  3: <MASK>
  4: <UNK>
  5: A
  6: C
  7: D
  8: E
  9: F
  10: G
  11: H
  12: I
  13: K
  14: L
  15: M
  16: N
  17: P
  18: Q
  19: R
  20: S
  21: T
  22: V
  23: W
  24: Y
token_to_id:
  <BOS>: 1
  <EOS>: 2
  <MASK>: 3
  <PAD>: 0
  <UNK>: 4
  A: 5
  C: 6
  D: 7
  E: 8
  F: 9
  G: 10
  H: 11
  I: 12
  K: 13
  L: 14
  M: 15
  N: 16
  P: 17
  Q: 18
  R: 19
  S: 20
  T: 21
  V: 22
  W: 23
  Y: 24
