dim: 128
decay: 0.99
codebook_size: 4096
commitment_weight: 0.5
orthogonal_reg_weight: 0
orthogonal_reg_max_codes: 512
orthogonal_reg_active_codes_only: True
rotation_trick: False
threshold_ema_dead_code: 2
kmeans_init: True
kmeans_iters: 10
stochastic_sample_codes: True
sample_codebook_temp: 0.1
alpha: 1.0
tik_tok:
  enabled: False
  compression_factor: 4
  residual_depth: 1
  classifier_weight: 0.1
  adaptive_coefficient: True
